### PR TITLE
Rename blank? to empty?

### PR DESCRIPTION
**Pull request by waynerobinson**
The #blank? method is only part of the active_suport gem. #empty?
is available in core Ruby.

### CODE REVIEW

**Comment by sharkzp** [comment]
But `blank?` will also return `false` for `nil`. While
```ruby
>> nil.empty?
NoMethodError: undefined method `empty?' for nil:NilClass
	from (irb):1
	from /Users/sharkzp/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
```
So you PR is not a renaming you actually change the functionality.

**Comment by waynerobinson** [comment]
I have also added a check for `#nil?`

ActiveSupport is a very heavy library to use just for `#blank?`.

**Comment by sharkzp** [comment]
Definitely :) But you could create this method as a helper method inside a gem. 
Because current conditions became hard to read. Also could you please check if there are tests for that?

**Comment by waynerobinson** [comment]
This is not hard to read and there aren't tests for anything at all… I don't have the time to commit to building a complete set of tests for this project so I can write a test for this argument checking code.

Monkey-patching `NilClass` to add `#blank?` is a bad idea anyway. 

Feel free to keep using `#blank?` however, you should add the active_support gem to your dependencies.

**Comment by Bossa573** [comment]
handled in other commits - thanks

**Pull request closed without merging**
